server {
    listen 8080;
    server_name _;
    server_tokens off;
    root /usr/share/nginx/html;
    index index.html;

    etag on;
    include /etc/nginx/security_headers.conf;

    location = / {
        expires -1;
        try_files /index.html =404;
    }

    location = /login {
        expires -1;
        try_files /index.html =404;
    }

    location = /login/ {
        expires -1;
        try_files /index.html =404;
    }

    location = /reset-password {
        expires epoch;
        try_files /index.html =404;
    }

    location = /reset-password/ {
        expires epoch;
        try_files /index.html =404;
    }

    location ~ "^/main\.[0-9a-f]{16}\.dart\.js$" {
        expires off;
        include /etc/nginx/security_headers.conf;
        add_header Cache-Control "public, max-age=31536000, immutable" always;
        try_files $uri =404;
    }

    location ~* \.mjs$ {
        default_type application/javascript;
        expires -1;
        try_files $uri =404;
    }

    location ~* \.(?:js|wasm|json)$ {
        expires -1;
        try_files $uri =404;
    }

    location ~* \.(?:css|png|jpg|jpeg|gif|svg|ico|woff|woff2)$ {
        expires 1d;
        try_files $uri =404;
    }

    location / {
        expires -1;
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
        expires -1;
    }
}
